admin:
  user:
   per_page: 5
  subject:
    per_page: 10
  suggested_question:
    per_page: 5

exam:
  per_page: 5
  start: "start"
  testing: "testing"
  unchecked: "unchecked"
  checked: "checked"
  status:
    checked: "checked"

labels:
  primary: "primary"
  warning: "warning"
  info: "info"
  success: "success"

suggested_question:
  status:
    :approved: "Approved"
    :rejected: "Rejected"

bollean:
  true: true
  false: false
