admin:
  user:
   per_page: 5
  subject:
    per_page: 10

exam:
  per_page: 5
  start: "start"
  testing: "testing"
  unchecked: "unchecked"
  checked: "checked"
  status:
    checked: "checked"

labels:
  primary: "primary"
  warning: "warning"
  info: "info"
  success: "success"

bollean:
  true: true
  false: false
